### PR TITLE
Added the Java Code for an Auto Service app.

### PR DESCRIPTION
**Pull request by OleseaRusnac**
Hi team, 
Please review my code and let me know if everything is correct.
Thanks in advance!

### CODE REVIEW

**Review by DimaSersun — APPROVED** [review]

**Review by arturrusnac — APPROVED** [review]
Everithing is perfect !
Nice code, and good JOB !

**Review by AndreiSecuQA — APPROVED** [review]
Happy to see you are going extra mile. Looks good to me, great job

**Comment by OleseaRusnac** [comment]
> Happy to see you are going extra mile. Looks good to me, great job

Thank you!

**Comment by OleseaRusnac** [comment]
> Everithing is perfect ! Nice code, and good JOB !
Thanks a lot!

**Pull request merged**
